export const Data = [
  {
    id: 1,
    product_name: "ATTA",
    brand: "AASHIRVAAD",
    quantity: "1 KG",
    price: "₹57",
    order_quantity: 0,
  },
  {
    id: 2,
    product_name: "MAIDA",
    brand: "AASHIRVAAD",
    quantity: "1 KG",
    price: "₹24",
    order_quantity: 0,
  },
  {
    id: 3,
    product_name: "GRAM MASALA",
    brand: "BHAGYALAKSHAMI",
    quantity: "500 G",
    price: "₹48",
    order_quantity: 0,
  },
  {
    id: 4,
    product_name: "RICE",
    brand: "BHAGYALAKSHAMI",
    quantity: "500 G",
    price: "₹41",
    order_quantity: 0,
  },
  {
    id: 5,
    product_name: "RICE",
    brand: "AASHIRVAAD",
    quantity: "500 G",
    price: "₹67",
    order_quantity: 0,
  },
  {
    id: 6,
    product_name: "ATTA - WHOLE WHEAT",
    brand: "BHAGYALAKSHAMI",
    quantity: "1 KG",
    price: "₹70",
    order_quantity: 0,
  },
  {
    id: 7,
    product_name: "MAGGY MASALA",
    brand: "MAGGY",
    quantity: "1 PC",
    price: "₹12",
    order_quantity: 0,
  },
];
